{% set name = "pennylane-lightning-gpu" %}
{% set version = "0.37.0" %}
{% set build_num = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3f70e3e3b7e4d0f6a679919c0c83e451e129666b021bb529dd02eb915d0666a0

build:
  number: {{ build_num }}
  skip: true  # [py==38 or (not linux) or not (cuda_compiler_version or "").startswith("12")]
  script: PL_BACKEND=lightning_gpu {{ PYTHON }} -m pip install . --no-deps -vv
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
  missing_dso_whitelist:
    - '*/libcuda.*'   # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja
  host:
    - libgomp          # [linux]
    - pip
    - pybind11
    - python
    - custatevec
    - cuda-cudart-dev  # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev    # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev  # [(cuda_compiler_version or "").startswith("12")]
    - cuda-version {{ cuda_compiler_version }}
  run:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    - pennylane >=0.37
    - python
test:
  imports:
    - pennylane_lightning
  commands:
    - python -c "import pennylane as qml; qml.about()"
    - pip check
  requires:
    - pip
about:
  home: https://docs.pennylane.ai/projects/lightning-gpu/en/latest/
  summary: The PennyLane-Lightning-GPU plugin extends the Pennylane-Lightning state-vector simulator written in C++, and offloads to the NVIDIA cuQuantum SDK for GPU accelerated circuit simulation.
  license: Apache-2.0
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE
  doc_url: https://docs.pennylane.ai/projects/lightning-gpu/en/latest/devices.html

extra:
  recipe-maintainers:
    - leofang
    - maliasadi
    - vincentmr
  feedstock-name: {{ name }}
