{% set name = "pennylane-lightning-gpu" %}
{% set version = "0.33.1" %}
{% set build_num = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 878f63cd1afadd52386b1aca9c0e3fb0a097b64ce8e347b325ebc7cac722e5e0

build:
  number: {{ build_num }}
  skip: true  # [(not linux) or (cuda_compiler_version not in ("11.2", "12.0"))]
  script: PL_BACKEND=lightning_gpu {{ PYTHON }} -m pip install . --no-deps -vv
  missing_dso_whitelist:
    - '*/libcuda.*'   # [linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja
    - pennylane >=0.33
  host:
    - {{ pin_compatible('custatevec', max_pin='x') }}
    - libgomp          # [linux]
    - pip
    - pybind11
    - python
    - cuda-cudart-dev  # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev    # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev  # [(cuda_compiler_version or "").startswith("12")]
    - cuda-version {{ cuda_compiler_version }}
  run:
    - {{ pin_compatible('custatevec', max_pin='x') }}
    - pennylane >=0.33
    - python
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
test:
  imports:
    - pennylane_lightning
    - pennylane_lightning.lightning_gpu
    - pennylane_lightning.lightning_gpu_ops
  commands:
    - python -c "import pennylane as qml; qml.about()"
    - pip check
  requires:
    - flaky
    - pip
    - pytest
    - pytest-mock
    - setuptools
about:
  home: https://docs.pennylane.ai/projects/lightning-gpu/en/latest/
  summary: The PennyLane-Lightning-GPU plugin extends the Pennylane-Lightning state-vector simulator written in C++, and offloads to the NVIDIA cuQuantum SDK for GPU accelerated circuit simulation.
  license: Apache-2.0
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE
  doc_url: https://docs.pennylane.ai/projects/lightning-gpu/en/latest/devices.html

extra:
  recipe-maintainers:
    - leofang
    - vincentmr
  feedstock-name: {{ name }}
